# Use Node.js base image 
FROM node:20

# Set working directory
WORKDIR /app

# Copy only package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci || npm install

# Copy the rest of the application code
COPY . .

# Expose Next.js dev server port
EXPOSE 3000

# Run Next.js in dev mode
CMD [ "npm", "run", "dev" ]