# Stage 1: build
FROM golang:1.24.7 AS builder

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Run go.mod download
RUN go mod download

# Copy the rest of the application code
COPY . .

# BUILD Go Application
RUN go build -o server ./cmd/server/

# Stage 2: Runtime
FROM debian:bookworm-slim

WORKDIR /app

# Copy the binary from the builder stage
COPY --from=builder /app/server /app/server 

# Expose port 8080 (backend listening port)
EXPOSE 8080

CMD ["./server"]